`--trace` option & New parsing with optional output file argument
MonoS/SupMover pull request #18
Opened 2024-02-07 00:03 UTC by YourMJK

See discussion: https://github.com/MonoS/SupMover/pull/17#issuecomment-1924849735

* Adds a new `--trace` option for printing structure and contents of segments
* Makes positional output file argument optional for actions that don't modify the input (like `--trace`)
* Replaces SEGFAULTs with standard parsing error when user inputs too few arguments
* Inline increment of argument index during parsing to reduce code clutter

2024-02-07 23:24 UTC, MonoS commented
Seems fine to me, I'll test it a bit tomorrow and let you know :)

2024-02-20 22:53 UTC, YourMJK commented
@MonoS Did you come around to testing this? Let me know if you want me to change something.

2024-02-21 18:22 UTC, MonoS commented
> Did you come around to testing this?

Yeah, i've put some comment in your code, i can see them in this PR before your latest comment.

2024-02-21 20:47 UTC, YourMJK commented
Oh, don't know why but I can't see those unfortunately ¯\_(ツ)_/¯

2024-02-23 09:13 UTC, MonoS commented
> Oh, don't know why but I can't see those unfortunately ¯\_(ツ)_/¯

That's probably because I don't know how to use github :)

Anyway:
- The new `--trace` doesn't have the check for its option without dash
- In the WDS you print both position and size in the same line, i'd split it in `Window frame position` and `Window frame size`
- In the WDS we check for multiple windows and report an error, i think we need those output only when doing modification, what do you think?

In any case I can see the code review from this link https://github.com/MonoS/SupMover/pull/18/files/8968b7ce51e5384b9684d1a867d82b3ef87393cb
And looks like this
![image](https://github.com/MonoS/SupMover/assets/801011/4b8f41c7-a07c-405b-b446-ef02779e9b1d)

2024-02-23 15:26 UTC, YourMJK commented
> That's probably because I don't know how to use github :)

That's fine, I'm not familiar with code review on GitHub either :)
But I think you need to click on "Review changes" and then "Submit review" for me to see it. Those comments are still pending (see your screenshot).

> * The new --trace doesn't have the check for its option without dash

That was on purpose since it's part of the old syntax and thus doesn't need to be backwards compatible.
But for consistency I can of course add that check as well.

Agreed on the other two points!

2024-02-23 17:13 UTC, MonoS requested changes

2024-02-24 14:25 UTC, YourMJK commented
Should be fixed now

2024-02-25 18:53 UTC, merged

2024-02-25 18:53 UTC, MonoS commented
Merged, thank you :)